# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - deploytestpri

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://astha0710.docker.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a7a31faf980d4c91907ec3112d367148 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2c8217ab9f1b40f3afd3d5ccf8bb43b4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: astha0710.docker.io/${{ secrets.AzureAppService_ContainerUsername_a7a31faf980d4c91907ec3112d367148 }}/deptest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'deploytestpri'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_18d5ef27d32e4556b40f8db8b6219d30 }}
        images: 'astha0710.docker.io/${{ secrets.AzureAppService_ContainerUsername_a7a31faf980d4c91907ec3112d367148 }}/deptest:${{ github.sha }}'